use_frameworks!

platform :ios, '8.0'

target 'DTTFoundation_Example' do
  pod 'DTTFoundation', :path => '../'

  target 'DTTFoundation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
